apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "nimby.fullname" . }}-schema-{{ .Release.Revision }}-{{ randAlphaNum 5 | lower }}
spec:
  parallelism: 1
  completions: 1
  backoffLimit: 10
  template:
    metadata:
      name: {{ template "nimby.fullname" . }}-schema
      labels: {{ include "nimby.labels" . | nindent 8 }}
    spec:
      activeDeadlineSeconds: 1800
      restartPolicy: Never
      imagePullSecrets:
        - name: dockerconfigjson-github-com
      containers:
        - env:
            - name: SQITCH_TARGET
              value: "db:pg:"
            - name: PGUSER
              value: postgres
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  key: password-superuser
                  name: {{ template "nimby.fullname" . }}-patroni
            - name: PGPORT
              value: "5432"
            - name: PGHOST
              value: {{ template "nimby.fullname" . }}-patroni
            - name: SQITCH_FULLNAME
              value: OpenShift Deployer
            - name: SQITCH_EMAIL
              value: deployer@pathfinder.gov.bc.ca
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
          name: {{ template "nimby.fullname" . }}-schema
          image: docker.pkg.github.com/bcgov/nr-megathon-auth-c-and-e/schema:main
          resources:
            limits:
              cpu: 500m
              memory: 128Mi
            requests:
              cpu: 100m
              memory: 64Mi
          command:
            - /usr/bin/env
            - bash
            - -c
            - |
              set -euo pipefail;
              cd schema;
              sqitch rebase -y;
