apiVersion: v1
kind: Secret
metadata:
  name: {{ template "nimby.fullname" . }}
  labels:
{{ include "nimby.labels" . | indent 4 }}
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-delete-policy": "before-hook-creation"
type: Opaque
data:
  database-user: {{ printf "metabase" | b64enc | quote }}
  database-password: {{ randAlphaNum 32 | b64enc | quote }}
