apiVersion: v2
name: nimby
description: A Helm chart for the Not in my Backyard instance
type: application
version: 0.2.2
appVersion: 0.36.3
dependencies:
  - name: cas-postgres
    version: 0.8.0
    repository: https://bcgov.github.io/cas-postgres/
  - name: metabase
    version: 0.12.1
    repository: file://../metabase
